#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor DisplayPort-2 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9

bspc config border_width	3
bspc config window_gap		20

bspc config split_ratio		0.5
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc config pointer_motion_interval 1
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

picom &
exec ~/.fehbg &
exec ~/.config/polybar/scripty.sh &
exec flameshot &
sleep 0.3
killall activeMonScript.sh
exec .scripts/activeMonScript.sh &
exec ~/.scripts/cleanfullscreen.sh &
