#! /bin/sh
confFolder='/home/bsp/.config/polybar'
config='/home/bsp/.config/polybar/config'
rm $config
echo ";;
;; DO NOT EDIT THIS FILE!
;; Configure polybar by editing the other files
;; and running the confScript.sh script
;;" >> $config
echo " " >> $config
cat $confFolder/elements >> $config
cat $confFolder/modules >> $config
cat $confFolder/bartypes >> $config
cat $confFolder/bars >> $config
