#! /bin/sh
rm config
echo ";;
;; DO NOT EDIT THIS FILE!
;; Configure polybar by editing the other files
;; and running the confScript.sh script
;;" >> config
echo " " >> config
cat elements >> config
cat modules >> config
cat bartypes >> config
cat bars >> config
